# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(default=uuid.uuid4, max_length=18, unique=True, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionId',
            field=models.UUIDField(default='01-000000000000001', editable=False, primary_key=True, serialize=False, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u0432 \u041e\u0431\u043b\u0430\u043a\u0435 \u042d\u0432\u043e\u0442\u043e\u0440'),
        ),
    ]
