# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190723_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deviceNumber',
            field=models.IntegerField(default=1, verbose_name='\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043d\u044b\u0445 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='planId',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0442\u0430\u0440\u0438\u0444\u0430'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trialPeriodDuration',
            field=models.CharField(default='P07DT', max_length=4, verbose_name='\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439 \u0431\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u043e\u0433\u043e \u043f\u0435\u0440\u0438\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='productId',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionId',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438'),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscriptions',
        ),
    ]
