# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190724_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trialPeriodDuration',
            field=models.CharField(default='P07DT', max_length=5, verbose_name='\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439 \u0431\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u043e\u0433\u043e \u043f\u0435\u0440\u0438\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('SubscriptionCreated', '\u043d\u043e\u0432\u0430\u044f \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430'), ('SubscriptionRenewed', '\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u043f\u0440\u043e\u0434\u043b\u0435\u043d\u0430 \u043d\u0430 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0438\u0439 \u043f\u0435\u0440\u0438\u043e\u0434'), ('AddonsUpdated', '\u0441\u043f\u0438\u0441\u043e\u043a \u043f\u043b\u0430\u0442\u043d\u044b\u0445 \u043e\u043f\u0446\u0438\u0439, \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0445 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c'), ('SubscriptionTerminated', '\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430'), ('SubscriptionTermsChanged', '\u0438\u0437\u043c\u0435\u043d\u0438\u043b\u0438\u0441\u044c \u0443\u0441\u043b\u043e\u0432\u0438\u044f \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438'), ('SubscriptionActivated', '\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u0430'), ('SubscriptionTerminationRequested', '\u0437\u0430\u043f\u0440\u043e\u0441 \u043d\u0430 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438')], default='SubscriptionCreated', max_length=40, verbose_name='\u0442\u0438\u043f \u0441\u043e\u0431\u044b\u0442\u0438\u044f'),
        ),
    ]
