# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190724_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
