# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations
import evotor.db


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190815_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=evotor.db.UserIdField(default=b'01-000000000000001', primary_key=True, serialize=False, unique=True, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f '),
        ),
    ]
