# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='planId',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0442\u0430\u0440\u0438\u0444\u0430'),
        ),
    ]
