# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20190726_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installationdata',
            options={'verbose_name': '\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u0447\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435', 'verbose_name_plural': '\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u0447\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f'),
        ),
    ]
