# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20190731_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438')),
                ('timestamp', models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
                ('version', models.IntegerField(default=1, verbose_name='\u0432\u0435\u0440\u0441\u0438\u044f API')),
                ('type', models.CharField(choices=[('ApplicationInstalled', '\u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e'), ('ApplicationUninstalled', '\u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u0443\u0434\u0430\u043b\u0435\u043d\u043e')], default='ApplicationInstalled', max_length=40, verbose_name='\u0442\u0438\u043f \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
            ],
            options={
                'db_table': 'installation_events',
                'verbose_name': '\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.AlterField(
            model_name='installationdata',
            name='installation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applications.InstallationEvent', verbose_name='uuid \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438 [\u0441\u043e\u0431\u044b\u0442\u0438\u0435]'),
        ),
        migrations.DeleteModel(
            name='Installation',
        ),
    ]
