# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-08 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20190805_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installation',
            options={'verbose_name': '\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u043e\u0435 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u044b\u0435 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='installationevent',
            options={'verbose_name': '\u0441\u043e\u0431\u044b\u0442\u0438\u0435 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f', 'verbose_name_plural': '\u0436\u0443\u0440\u043d\u0430\u043b \u0441\u043e\u0431\u044b\u0442\u0438\u0439 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u043a \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0439'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': '\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u043d\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0436\u0443\u0440\u043d\u0430\u043b \u043f\u043e\u0434\u043f\u0438\u0441\u043e\u043a \u043d\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435'},
        ),
        migrations.AlterField(
            model_name='installation',
            name='installation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applications.InstallationEvent', verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0441\u043e\u0431\u044b\u0442\u0438\u044f [\u0441\u043e\u0431\u044b\u0442\u0438\u0435]'),
        ),
        migrations.AlterField(
            model_name='installationevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0441\u043e\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='installationevent',
            name='timestamp',
            field=models.BigIntegerField(verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0441\u043e\u0431\u044b\u0442\u0438\u044f'),
        ),
    ]
