# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-08 05:20
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20190808_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationevent',
            name='timestamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0441\u043e\u0431\u044b\u0442\u0438\u044f'),
        ),
    ]
