# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-21 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20190820_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='installation',
        ),
        migrations.AddField(
            model_name='installationevent',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.Installation', verbose_name='\u0434\u0430\u043d\u043d\u044b\u0435 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438'),
            preserve_default=False,
        ),
    ]
