# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-21 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20190821_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installation',
            old_name='installation',
            new_name='installationId',
        ),
    ]
