# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-26 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20190821_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='installationId',
            field=models.ForeignKey(db_column='installation_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='applications.InstallationEvent', verbose_name='\u0434\u0430\u0442\u0430 \u0438 \u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0441\u043e\u0431\u044b\u0442\u0438\u044f [\u0441\u043e\u0431\u044b\u0442\u0438\u0435]'),
        ),
    ]
