# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-13 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_auto_20190907_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='userId',
            field=models.ForeignKey(db_column='user_id', default=b'01-000000000000001', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u042d\u0432\u043e\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u0432 \u041e\u0431\u043b\u0430\u043a\u0435 \u042d\u0432\u043e\u0442\u043e\u0440'),
        ),
    ]
