# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_auto_20191020_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='productId',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f'),
        ),
    ]
