# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-21 23:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_auto_20191020_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installationevent',
            options={'verbose_name': '\u0441\u043e\u0431\u044b\u0442\u0438\u0435 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0438\u043b\u0438 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f', 'verbose_name_plural': '\u0436\u0443\u0440\u043d\u0430\u043b \u0441\u043e\u0431\u044b\u0442\u0438\u0439 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u043a \u0438 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u0439 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0439'},
        ),
        migrations.AddField(
            model_name='installation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installation',
            name='installationId',
            field=models.ForeignKey(db_column='installation_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='applications.InstallationEvent', verbose_name='\u0442\u0435\u043a\u0443\u0449\u0438\u0439 \u0441\u0442\u0430\u0442\u0443\u0441 [\u0434\u0430\u0442\u0430 \u0441\u043e\u0431\u044b\u0442\u0438\u044f]'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='productId',
            field=models.ForeignKey(db_column='product_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='applications.Application', verbose_name='\u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u042d\u0432\u043e\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='userId',
            field=models.ForeignKey(db_column='user_id', default=b'01-000000000000001', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u042d\u0432\u043e\u0442\u043e\u0440'),
        ),
    ]
