# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarCode',
            fields=[
                ('code', models.CharField(default='0123456789101', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434')),
            ],
            options={
                'db_table': 'barcodes',
                'verbose_name': '\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434',
                'verbose_name_plural': '\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430 \u0438\u043b\u0438 \u0433\u0440\u0443\u043f\u043f\u044b \u0442\u043e\u0432\u0430\u0440\u043e\u0432')),
                ('group', models.BooleanField(verbose_name='\u044f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u0433\u0440\u0443\u043f\u043f\u043e\u0439')),
                ('type', models.CharField(choices=[('NORMAL', '\u043e\u0431\u044b\u0447\u043d\u044b\u0439'), ('ALCOHOL_MARKED', '\u043c\u0430\u0440\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044c'), ('ALCOHOL_NOT_MARKED', '\u043d\u0435\u043c\u0430\u0440\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044c'), ('TOBACCO_MARKED', '\u043c\u0430\u0440\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0430\u0431\u0430\u043a'), ('SERVICE', '\u0443\u0441\u043b\u0443\u0433\u0430 (\u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d \u043d\u0430 \u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043b\u0430\u0445 \u043d\u0430\u0447\u0438\u043d\u0430\u044f \u0441 \u043f\u0440\u043e\u0448\u0438\u0432\u043a\u0438 3.0)')], default='NORMAL', max_length=20, verbose_name='\u0442\u0438\u043f \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0442\u043e\u0432\u0430\u0440\u0430 \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438')),
                ('measureName', models.CharField(blank=True, default='\u0448\u0442', max_length=15, verbose_name='\u0435\u0434\u0438\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('tax', models.CharField(choices=[('NO_VAT', b'\xd0\x9d\xd0\x94\xd0\xa1 \xd0\xbd\xd0\xb5 \xd0\xbe\xd0\xb1\xd0\xbb\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb5\xd1\x82\xd1\x81\xd1\x8f'), ('VAT_10', b'\xd0\x9d\xd0\x94\xd0\xa1 10%'), ('VAT_18', b'\xd0\x9d\xd0\x94\xd0\xa1 18%'), ('VAT_0', b'\xd0\x9d\xd0\x94\xd0\xa1 0%'), ('VAT_18_118', b'\xd0\x9d\xd0\x94\xd0\xa1 18/118'), ('VAT_10_110', b'\xd0\x9d\xd0\x94\xd0\xa1 10/110')], default='NO_VAT', max_length=10, verbose_name='c\u0442\u0430\u0432\u043a\u0430 \u041d\u0414\u0421 \u0434\u043b\u044f \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='\u043e\u0442\u043f\u0443\u0441\u043a\u043d\u0430\u044f \u0446\u0435\u043d\u0430 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('allowToSell', models.BooleanField(default=True, verbose_name='\u0440\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u0438\u0435 \u043d\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0443 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('costPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='\u0437\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('articleNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0430\u0440\u0442\u0438\u043a\u0443\u043b \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u041a\u043e\u0434 \u0442\u043e\u0432\u0430\u0440\u0430 \u0438\u043b\u0438 \u0433\u0440\u0443\u043f\u043f\u044b \u0442\u043e\u0432\u0430\u0440\u043e\u0432')),
                ('barCodes', models.ManyToManyField(null=True, to='products.BarCode', verbose_name='\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434\u044b')),
                ('parentUuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='\u043f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u043d\u043e\u0441\u0442\u044c \u043a \u0433\u0440\u0443\u043f\u043f\u0435 \u0442\u043e\u0432\u0430\u0440\u043e\u0432')),
            ],
            options={
                'db_table': 'products',
                'verbose_name': '\u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440\u044b',
            },
        ),
    ]
