# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barCodes',
            field=models.ManyToManyField(to='products.BarCode', verbose_name='\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434\u044b'),
        ),
    ]
