# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191128_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcocodes_code', to='products.AlcoCode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcocodes_product', to='products.Product')),
            ],
            options={
                'db_table': 'alcocodes_table',
                'verbose_name': '\u0430\u043b\u043a\u043e\u043a\u043e\u0434',
                'verbose_name_plural': '\u0430\u043b\u043a\u043e\u043a\u043e\u0434\u043a\u043e\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='BarCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes_code', to='products.BarCode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes_product', to='products.Product')),
            ],
            options={
                'db_table': 'barcodes_table',
                'verbose_name': '\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434',
                'verbose_name_plural': '\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434\u044b',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='alcoCodes',
            field=models.ManyToManyField(through='products.AlcoCodes', to='products.AlcoCode', verbose_name='\u0410\u043b\u043a\u043e\u043a\u043e\u0434\u044b'),
        ),
        migrations.AddField(
            model_name='product',
            name='barCodes',
            field=models.ManyToManyField(through='products.BarCodes', to='products.BarCode', verbose_name='\u0448\u0442\u0440\u0438\u0445\u043a\u043e\u0434\u044b'),
        ),
    ]
